name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./Chemorization-App
        run: npm install

      - name: Lint and Test
        working-directory: ./Chemorization-App
        run: npm run lint && npm test

      - name: Build (Optional)
        working-directory: ./Chemorization-App
        run: echo "build steps go here"
